# Generated by Django 3.1 on 2020-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=255, unique=True, verbose_name='登录名')),
                ('login_url', models.CharField(max_length=512, verbose_name='登录url')),
                ('redirect', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='重定向url')),
                ('username', models.CharField(max_length=128, verbose_name='登录用户名')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
                ('browser_type', models.CharField(choices=[('Chrome', '谷歌浏览器'), ('Firefox', '火狐浏览器'), ('IE', 'IE浏览器'), ('Chrome_incognito_window', '谷歌浏览器隐身窗口'), ('Firefox_incognito_window', '火狐浏览器隐身窗口'), ('IE_incognito_window', 'IE浏览器隐身窗口')], default='Chrome', max_length=64, verbose_name='浏览器类型')),
                ('close_window_method', models.SmallIntegerField(choices=[(0, '新增页签窗口打开'), (1, '关闭浏览器重新打开')], default=0, verbose_name='打开窗口方式')),
                ('user_role', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户角色')),
                ('quarter', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户岗位')),
                ('data_range', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='数据范围')),
                ('remark', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '登录数据',
                'verbose_name_plural': '登录数据',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
